# Generated by Django 4.0.5 on 2023-07-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='آدرس ایمیل')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='نام کاربری')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='نام خانوادگی')),
                ('image', models.ImageField(blank=True, default='img/profiles/default.png', upload_to='img/profiles')),
                ('about', models.TextField(blank=True, max_length=500, verbose_name='درباره')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='موبایل')),
                ('postcode', models.CharField(blank=True, max_length=12, verbose_name='کد پستی')),
                ('address_line_1', models.CharField(blank=True, max_length=150, verbose_name='آدرس')),
                ('address_line_2', models.CharField(blank=True, max_length=150, verbose_name='ادامه آدرس')),
                ('town_city', models.CharField(blank=True, max_length=150, verbose_name='شهر')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('is_staff', models.BooleanField(default=False, verbose_name='کارمند')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='آخرین فعالیت')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'نمایه کاربری',
                'verbose_name_plural': 'نمایه کاربری',
            },
        ),
    ]
