# Generated by Django 4.0.5 on 2022-08-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
    ]
