# Generated by Django 4.0.5 on 2023-07-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_person_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره حساب بانکی'),
        ),
    ]
