# Generated by Django 4.0.5 on 2022-08-23 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_alter_person_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='id_code',
        ),
    ]
