# Generated by Django 4.0.5 on 2022-08-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_rename_rule_warrant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrant',
            name='base_years',
            field=models.IntegerField(blank=True, null=True, verbose_name='سنوات'),
        ),
    ]
