# Generated by Django 4.0.5 on 2022-08-23 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salary', '0003_alter_warrant_base_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryreceipt',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wage_creator', to=settings.AUTH_USER_MODEL, verbose_name='تهیه کننده'),
            preserve_default=False,
        ),
    ]
