# Generated by Django 4.0.5 on 2023-07-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0003_alter_baseinfo_base_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryreceipt',
            name='insurance',
            field=models.IntegerField(default=0, verbose_name='حق بیمه'),
        ),
        migrations.AddField(
            model_name='salaryreceipt',
            name='loan_received',
            field=models.IntegerField(default=0, verbose_name='وام دریافتی'),
        ),
        migrations.AddField(
            model_name='salaryreceipt',
            name='other_deductions',
            field=models.IntegerField(default=0, verbose_name='سایر کسورات'),
        ),
        migrations.AddField(
            model_name='salaryreceipt',
            name='sub_total_deductions',
            field=models.IntegerField(default=0, verbose_name='جمع کسورات'),
        ),
        migrations.AddField(
            model_name='salaryreceipt',
            name='tax',
            field=models.IntegerField(default=0, verbose_name='مالیات'),
        ),
        migrations.AlterField(
            model_name='salaryreceipt',
            name='closed_work_wage',
            field=models.IntegerField(default=0, verbose_name='مبلغ تعطیل کاری'),
        ),
        migrations.AlterField(
            model_name='salaryreceipt',
            name='mission_wage',
            field=models.IntegerField(default=0, verbose_name='مأموریت'),
        ),
        migrations.AlterField(
            model_name='salaryreceipt',
            name='monthly_wage',
            field=models.IntegerField(default=0, verbose_name='حقوق ماهیانه'),
        ),
        migrations.AlterField(
            model_name='salaryreceipt',
            name='overtime_wage',
            field=models.IntegerField(default=0, verbose_name='اضافه کاری'),
        ),
        migrations.AlterField(
            model_name='salaryreceipt',
            name='right_of_children',
            field=models.IntegerField(default=0, verbose_name='حق اولاد'),
        ),
        migrations.AlterField(
            model_name='salaryreceipt',
            name='right_of_grocery',
            field=models.IntegerField(default=0, verbose_name='حق خوار و بار'),
        ),
        migrations.AlterField(
            model_name='salaryreceipt',
            name='right_of_house',
            field=models.IntegerField(default=0, verbose_name='حق مسکن'),
        ),
        migrations.AlterField(
            model_name='salaryreceipt',
            name='sub_total_wage',
            field=models.IntegerField(default=0, verbose_name='جمع حقوق و مزایا'),
        ),
    ]
