# Generated by Django 4.0.5 on 2022-08-23 23:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0004_salaryreceipt_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryreceipt',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='ایجاد شده در'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salaryreceipt',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='به روز رسانی در'),
        ),
    ]
