# Generated by Django 4.0.5 on 2022-08-23 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_remove_person_id_code'),
        ('salary', '0005_salaryreceipt_created_salaryreceipt_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryreceipt',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wage_person', to='person.person', verbose_name='شخص'),
        ),
    ]
