# Generated by Django 4.0.5 on 2022-08-26 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_remove_person_id_code'),
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salary', '0007_alter_salaryreceipt_closed_work_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='سال')),
                ('type_of_rule', models.CharField(choices=[('Private', 'خصوصی'), ('Government', 'دولتی'), ('Retireds', 'بازنشستگان')], default='Private', max_length=20, verbose_name='نوع حکم')),
                ('base_salary', models.IntegerField(verbose_name='حقوق پایه')),
                ('base_years', models.IntegerField(blank=True, null=True, verbose_name='سنوات')),
                ('reward', models.IntegerField(blank=True, null=True, verbose_name='پاداش')),
                ('right_to_housing', models.IntegerField(blank=True, null=True, verbose_name='حق مسکن')),
                ('right_to_grocery', models.IntegerField(blank=True, null=True, verbose_name='حق خوار و بار')),
                ('right_to_supervisor', models.IntegerField(blank=True, null=True, verbose_name='حق سرپرستی')),
                ('service_location', models.CharField(blank=True, max_length=50, null=True, verbose_name='محل خدمت')),
                ('job_title', models.CharField(max_length=50, verbose_name='عنوان شغل')),
                ('organizational_unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='واحد سازمانی')),
                ('organizational_position', models.CharField(blank=True, max_length=50, null=True, verbose_name='پست سازمانی')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='به روز رسانی در')),
                ('company', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='decree_company', to='company.company', verbose_name='شرکت')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decree_creator', to=settings.AUTH_USER_MODEL, verbose_name='تهیه کننده')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decree_person', to='person.person', verbose_name='شخص')),
                ('type_of_employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salary.typeofemployment', verbose_name='نوع استخدام')),
            ],
            options={
                'verbose_name': 'حکم حقوقی',
                'verbose_name_plural': 'حکم حقوقی',
                'ordering': ('-created',),
            },
        ),
        migrations.DeleteModel(
            name='Warrant',
        ),
    ]
