# Generated by Django 4.0.5 on 2022-09-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0010_alter_salaryreceipt_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryreceipt',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
