# Generated by Django 4.0.5 on 2022-09-04 13:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0011_alter_salaryreceipt_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryreceipt',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
