# Generated by Django 4.0.5 on 2022-09-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0013_alter_salaryreceipt_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryreceipt',
            name='closed_work_wage',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
        migrations.AddField(
            model_name='salaryreceipt',
            name='mission_wage',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
        migrations.AddField(
            model_name='salaryreceipt',
            name='monthly_wage',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
        migrations.AddField(
            model_name='salaryreceipt',
            name='overtime_wage',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
        migrations.AddField(
            model_name='salaryreceipt',
            name='right_of_children',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
        migrations.AddField(
            model_name='salaryreceipt',
            name='right_of_grocery',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
        migrations.AddField(
            model_name='salaryreceipt',
            name='right_of_house',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
        migrations.AddField(
            model_name='salaryreceipt',
            name='sub_total_wage',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
    ]
