# Generated by Django 4.0.5 on 2022-09-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0014_salaryreceipt_closed_work_wage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='decree',
            name='right_of_children',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='حق اولاد'),
        ),
        migrations.AlterField(
            model_name='decree',
            name='base_salary',
            field=models.IntegerField(default=0, verbose_name='حقوق پایه'),
        ),
        migrations.AlterField(
            model_name='decree',
            name='base_years',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='سنوات'),
        ),
        migrations.AlterField(
            model_name='decree',
            name='reward',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='پاداش'),
        ),
        migrations.AlterField(
            model_name='decree',
            name='right_to_grocery',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='حق خوار و بار'),
        ),
        migrations.AlterField(
            model_name='decree',
            name='right_to_housing',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='حق مسکن'),
        ),
        migrations.AlterField(
            model_name='decree',
            name='right_to_supervisor',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='حق سرپرستی'),
        ),
    ]
