# Generated by Django 4.0.5 on 2022-10-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='start_of_activity',
            field=models.CharField(max_length=10, verbose_name='تاریخ شروع فعالت'),
        ),
    ]
