# Generated by Django 4.0.5 on 2023-07-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_company_start_of_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='start_of_activity',
            field=models.DateField(default='2023-07-13 00:00:00', verbose_name='تاریخ شروع فعالت'),
        ),
    ]
