# Generated by Django 4.0.5 on 2023-07-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_company_start_of_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='start_of_activity',
            field=models.DateField(default='23/07/13 _ 00:00:00', verbose_name='تاریخ شروع فعالت'),
        ),
    ]
