# Generated by Django 4.0.5 on 2023-08-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_alter_company_start_of_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='start_of_activity',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ شروع فعالت'),
        ),
    ]
